### ISSUE TITLE
有符號就走樣

### ISSUE THREAD

**Issue by LibelLists** [kitce/libel#12]
被標籤會員名, 標籤名, 標籤原因有符號就走樣

**Comment by kitce** [comment]
未能重現問題

![image](https://user-images.githubusercontent.com/15712798/162805279-9d1f8292-d267-44c7-a344-6181024659f6.png)

![image](https://user-images.githubusercontent.com/15712798/162806097-41c59e4d-195b-4872-a90c-25a9af44238b.png)

**Comment by LibelLists** [comment]
https://na.cx/i/GrPVdQS.png
https://na.cx/i/LUHr4Xx.png

因為會走樣 所以要用到好似=同/嘅code都唔會正常用到啲原有功能
