### ISSUE TITLE
更新天朝犬隻list之後subscribe唔到

### ISSUE THREAD

**Issue by DynastyDog** [kitce/libel#19]
423人個list仲用到，但更新至428人之後subscribe唔到
![IMG_8138](https://github.com/kitce/libel/assets/114913717/58649b2a-654e-4573-8cab-6d941eadbcac)
![IMG_8139](https://github.com/kitce/libel/assets/114913717/284aac90-689c-4627-92e0-657ed6a45cb2)

**Comment by 3amPKX4WrH** [comment]
我睇咗你之前個JSON
```json
"263485": [
   {
    "id": "1",
    "text": "on9",
    "reason": "話「我提議： 波罩運動！」",
    "url": "https://lihkg.com/thread/3386883/page/6",
    "date": 1683960581662,
    "source": {
     "thread": 1411487,  <---- 格式係string
     "page": 1,
     "messageNumber": 1 <---- 格式係string
    },
    "image": "https://na.cx/i/53a2OxS.png"
   },
```

雖然呢兩個屬性都應該係number
但佢set死咗做string

**Comment by DynastyDog** [comment]
想問下點解個messagenumber會變左做int, 明明平時都係咁入list
![Screenshot 2023-05-28 165026](https://github.com/kitce/libel/assets/114913717/b15ec6db-6040-4c2f-8ef3-72a091e8bccb)

**Comment by DynastyDog** [comment]
> 
係我問題, open個json個用encoding="utf8", '123'變左做123

**Comment by DynastyDog** [comment]
cast返做str就解決左
