### ISSUE TITLE
在Firefox以Greasemonkey安裝Libel後無法標籤會員

### ISSUE THREAD

**Issue by HJackal** [kitce/libel#2]
**Describe the bug**
在Firefox以Greasemonkey安裝Libel後，標籤按鈕沒有字，滑鼠點擊無反應；如使用Tampermonkey 4.15.6154則運作正常。

**To Reproduce**
1. 安裝Firefox 97.0.2
2. 安裝Greasemonkey 4.11
3. 安裝Libel 2.2.2
4. 登入Lihkg.com
5. 點擊會員名稱

**Expected behavior**
【會員資料】小視窗右下方出現【標籤】字樣，點擊後彈出【新增標籤】小視窗

**Screenshots**
![Screenshot 2022-03-10 194431](https://user-images.githubusercontent.com/101329144/157656639-d30ef3b6-155e-49b0-83ed-ccba68283b7e.png)

**Desktop:**
 - Windows 10 Pro OS build 19043.1526
 - Firefox 97.0.2 (64-bit)
 - Greasemonkey 4.11
 - Libel 2.2.2

**Comment by kitce** [comment]
已確認 Greasemonkey 及 Tampermonkey 都有相同問題
問題不穩定，未知實際重現步驟

但標籤按鍵已於 [v3.3.0](https://github.com/kitce/libel/releases/tag/v3.3.0) 被重新設計及佈置
如果仍有類似問題再重開此 Issue
