### ISSUE TITLE
合併重覆標籤及提供常用名稱標籤清單

### ISSUE THREAD

**Issue by HJackal** [kitce/libel#3]
訂閱多個名單後，知名會員經常出現一串相同或相近標籤，或者同一標籤因不同原因重覆出現。
建議加入合併功能，於同一標籤顯示多個名單及原因。
另外可建立常用名稱標籤清單，方便合併及省略重覆輸入標籤的時間。

**Comment by kitce** [comment]
相關功能已新增於 [v3.1.0](https://github.com/kitce/libel/releases/tag/v3.1.0)
