### ISSUE TITLE
標籤制失蹤

### ISSUE THREAD

**Issue by PikachuEXE** [kitce/libel#4]
**Describe the bug**
無法睇到標籤制

**Screenshots**
![image](https://user-images.githubusercontent.com/1018543/159118740-0e49ab28-5f53-4df4-971e-82578726e427.png)
![image](https://user-images.githubusercontent.com/1018543/159118783-bf5c3b7a-667c-4d6c-a545-2321b7494564.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Vivaldi
 - Version: 5.1.2567.66 (Stable channel) (64-bit)

**Additional context**
由於我有安裝多種adblock插件，所以有機會由佢地做成
但我已試過全部停用一樣有事

**Comment by kitce** [comment]
Same issue as #2
