### ISSUE TITLE
標籤冇顯示

### ISSUE THREAD

**Issue by LibelLists** [kitce/libel#7]
簡略短回覆嘅標籤冇出現
狙擊掣同標籤掣正常出現

**Comment by kitce** [comment]
未發現相關問題

版本 v3.4.1

簡短回覆（未點擊）
![image](https://user-images.githubusercontent.com/15712798/161605711-37b8a399-f229-4127-bb93-fd6126975236.png)

簡短回覆（已點擊展開）
![image](https://user-images.githubusercontent.com/15712798/161605767-910b875c-30cc-4752-9381-4a757930d420.png)

**Comment by LibelLists** [comment]
問題屬於v3.4.1之前
