### ISSUE TITLE
post內特定情況下標籤功能失效

### ISSUE THREAD

**Issue by LibelLists** [kitce/libel#8]
同一頁內被封鎖會員打後嗰班
非封鎖會員冇標籤,冇標籤/狙擊掣
被封鎖會員基本正常
被封鎖+簡略短回覆冇標籤

然後去下一頁又會重複返上一頁同樣問題

**Comment by kitce** [comment]
相關問題已修正於 [v3.4.1](https://github.com/kitce/libel/releases/tag/v3.4.1)
